### ISSUE TITLE
可否通过配置，在获取boolean类型数据时，返回0/1 而不是 true/false

### ISSUE THREAD

**Issue by aiping312** [apache/iotdb#1565]
可否通过配置，在获取boolean类型数据时，返回0/1 而不是 true/false.

**Comment by jixuan1989** [comment]
在增加这个功能之前，可以通过以下两种方式来达到你想要的输出：
1.使用jdbc的话，resultset的getBoolean方法返回的就是布尔型，自己定义输出就行；
2.使用session api的话，使用sessionDataSet的getObjectValue()方法而不是getStringValue()方法，就可以得到布尔型，再自行输出。

before we add this feature, if you want to return 0/1 rather than true/false, try:
1. when  you use JDBC, call `resultset.getBoolean()` method
2. when you use session API, call `sessionDataSet.getObjectValue() rather than getStringValue()`

**Comment by qiaojialin** [comment]
我们可以改动一下 getString 方法，将 bool 类型的 getString 按照配置文件转化为 0/1 或者 true/false

We could refactor the getString() method to return 0/1 or true/false for a boolean value depending on the configuration.
