### ISSUE TITLE
IoTDB是否支持自动重连功能 （Does Session support reconnect?）

### ISSUE THREAD

**Issue by ATM006** [apache/iotdb#1719]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ATM006** [comment]
500qps出现session自动断开

**Comment by qiaojialin** [comment]
SessionPool 支持重连，不过如果客户端爆了运行异常，会连接泄漏，可以拉一下 rel/0.10 分支手动打包，在0.10.2-SNAPSHOT 版本修了

The SessionPool could reconnect when meet error. However, if you have RunTimeException in client, the connection will leak, we fixed this in rel/0.10 (0.10.2-SNAPSHOT).

另外，能提供复现程序吗？

**Comment by ATM006** [comment]
我用的是0.10.0版本的docker镜像session  ，这个版本的镜像支持自动重连吗

**Comment by qiaojialin** [comment]
只有 SessionPool 有自动重连，如果镜像有 SessionPool，那应该是支持的。自动断开的日志有吗

**Comment by ATM006** [comment]
我用的是session而不是 SessionPool，我先试一下SessionPool。有问题再回来~

**Comment by jixuan1989** [comment]
If you want to reconnect the server if the network is broken because the network problem or some others in the client side, it is ok to use sessionPool in 0.10.1.
 But there is a bug for reconnecting the server (if the server is restarted) when using sessionPool in 0.10.1. 
you can compile source code from rel/0.10 or master branch to get a bug-fix version.

如果你想在客户端网络出问题时重连，0.10.1的sessionPool就可以。
但是这个版本在服务器重启的情况下，sessionPool有个重连的bug。已经在rel/0.10和master分支上修复了。

**Comment by qiaojialin** [comment]
Reconnection of session is supported in 0.11~

0.11 版本支持 session 的重连啦
