### ISSUE TITLE
I want to know the detail design for tag inverted index

### ISSUE THREAD

**Issue by flashmouse** [apache/iotdb#1833]
Hi for now we are learning the project iotdb whether it meet our usage scenario.

When we check the code(v0.10.1), we notice the tag inverted-index seems very simple. It's only a hashmap attribute in  MManager, and the only query function use it is **getAllTimeseriesSchema**, this function only could filter timeseries query with one tag.

I want to know whether iotdb could do query with one tag used, and whether iotdb's tag index is just a hashmap all in memory?  

thx..

**Comment by JackieTien97** [comment]
It is indeed just a hashmap attribute and persisted within mlog.txt. The detailed design document is as following:

Firstly, we support two kind property for one timeseries: tag and attribute. The only diiference betwwen them is that we will maintain an inverted index on the tag, so we can use tag property in the where clause.

The create timeseries clause will be changed like:

CREATE TIMESERIES fullPath alias? WITH attributeClauses
alias
    : LR_BRACKET ID RR_BRACKET
    ;
attributeClauses
    : DATATYPE OPERATOR_EQ dataType COMMA ENCODING OPERATOR_EQ encoding
    (COMMA (COMPRESSOR | COMPRESSION) OPERATOR_EQ compressor=propertyValue)?
    tagClause
    attributeClause
    ;

attributeClause
    : (ATTRIBUTES LR_BRACKET property (COMMA property)* RR_BRACKET)?
    ;

tagClause
    : (TAGS LR_BRACKET property (COMMA property)* RR_BRACKET)?
    ;


Notice that we also support an alias for this time series while creating it. We will maintain another alias map in the deviceNode. In this way, we can also use the alias to do query, same as the measurement name.

The tag and attribute info will be persisted to another metadata file named tlog.txt in the same directory as mlog.txt.

The total length of the tag and attribute for one series is fixed to tag_attribute_total_size which you can change in the iotdb-engine.properties. When we need to update the value of one tag or attribute, we can read all of them and change the value we want and rewrite them back to the same position. Surely, the later value should not make the total length exceed the tag_attribute_total_size.

The content in the tlog.txt will be like:
tagsSize (tag1=v1, tag2=v2) attributesSize (attr1=v1, attr2=v2)

The offset of tag/attribute info for one time series in the tlog.txt will be saved in the mlog.txt. In that way, we only need to load the offset into memory instead of loading all the content of the tlog.txt into memory.
Currently, one line record for create timeseries  in the mlog.txt will be like:

cmd, path,                       TSDataType,  TSEncoding, CompressionType,[properties],  [alias],            [tag/attribute offset]
0     , root.turbine.d1.s1, 3,                     2,                   1,                           ,                    ,  temperature, -1

If the timeseries has no tag/attribute info, the offset will be -1.

There will be one more step while initializing the MMangager in case of restarting, that’s we will also load and deserialize the tag info through offset in the mlog.txt into the inverted index map in the MManager.

Secondly, I will also extend the show timeseries syntax like:

SHOW TIMESERIES prefixPath? showWhereClause?

showWhereClause
    : WHERE (property | containsExpression)
    ;
containsExpression
    : name=ID OPERATOR_CONTAINS value=propertyValue
    ;

The property in the where clause must be a tag or it will throw an exception.

If there is no where clause, the show timeseries query process will be same as before. 
However if there is a where clause, we will use the inverted index map in the MManager to find all the satisfied LeafMNode and filter the by the prefixPath.

**Comment by flashmouse** [comment]
thank you for your detailed description!

from your comment above, and the system design article in iotdb official website, I think you do great job with the timeseries data format to achieve the best compression ratio and  query&write performance.  but I still doubt whether the tag index design now could work well:

- tag index just a hashmap, it could mean lots of potential probelm, if multi timeseries created, all of them should wait the write lock, it's a concurrency write performance.
- If query series device by sequence, hashmap couldn't do well in such situation.
- have you test the performance when large number devices write to db, such as billiion devices, it may face many times of hashmap expansion.  and so the query performance  include where clause.
- all index saved in memory may lead to system unstable and need expensive machine. influxdb in older version save tag index all in memory, seems a bad attemp(although now they still do bad, too). also it mean mmanger component need lots of memory. for now iotdb seems doesn't implement a distributed program, this more worst. 
- I guess when device quantity increase to a big number, it would take lots of time for iotdb to restart and recover. 
- and so on.

in our tsdb maintain experience, tag index is a very important part, develpoer & user should design and use it carefully. for example, if user write a tag with long text string, it could cause index use more mem, and drop down system availability.

our company have now billion device, we are planning to test tdengine & iotdb to verify whether they could meet our requirement. tdengine programmed by c, it's little hard for us to maintain it, and iotdb seems have some problem too(not distributed system, seems simple index). 

If you have any advice, please tell us, thanks!

----------------------------------

顺便问下能不能直接和你们的开发人员沟通。我看你们github回复有点慢， apache mail list也不咋活跃，官网上提到有钉钉，但是我不想用钉钉。。

**Comment by qiaojialin** [comment]
您好，加个微信吧 qiaojialin1993

**Comment by JackieTien97** [comment]
> thank you for your detailed description!
> 
> from your comment above, and the system design article in iotdb official website, I think you do great job with the timeseries data format to achieve the best compression ratio and query&write performance. but I still doubt whether the tag index design now could work well:
> 
> * tag index just a hashmap, it could mean lots of potential probelm, if multi timeseries created, all of them should wait the write lock, it's a concurrency write performance.
> * If query series device by sequence, hashmap couldn't do well in such situation.
> * have you test the performance when large number devices write to db, such as billiion devices, it may face many times of hashmap expansion.  and so the query performance  include where clause.
> * all index saved in memory may lead to system unstable and need expensive machine. influxdb in older version save tag index all in memory, seems a bad attemp(although now they still do bad, too). also it mean mmanger component need lots of memory. for now iotdb seems doesn't implement a distributed program, this more worst.
> * I guess when device quantity increase to a big number, it would take lots of time for iotdb to restart and recover.
> * and so on.
> 
> in our tsdb maintain experience, tag index is a very important part, develpoer & user should design and use it carefully. for example, if user write a tag with long text string, it could cause index use more mem, and drop down system availability.
> 
> our company have now billion device, we are planning to test tdengine & iotdb to verify whether they could meet our requirement. tdengine programmed by c, it's little hard for us to maintain it, and iotdb seems have some problem too(not distributed system, seems simple index).
> 
> If you have any advice, please tell us, thanks!
> 
> 顺便问下能不能直接和你们的开发人员沟通。我看你们github回复有点慢， apache mail list也不咋活跃，官网上提到有钉钉，但是我不想用钉钉。。

确实是的，我们目前对于时间序列的tag的倒排索引的实现比较native，在大数据量情况下会有问题。
BTW，我们的分布式版本也正在内测阶段，在cluster_new分支，也有相应的设计文档，您可以在对应分支看到。

我的微信号是JackieTien，有什么疑问，微信响应的快一些。

**Comment by flashmouse** [comment]
是的我已经和 @qiaojialin 在微信上沟通过了, 期待后续的更新。

hope iotdb better and better!
