### ISSUE TITLE
Data missing

### ISSUE THREAD

**Issue by kohlersDagger** [apache/iotdb#2158]
**Describe**
In the process of writing iotdb, it is found that the historical data is decreasing

**To Reproduce**
1.  iotdb:0.11.0 : Keep the default settings & 40 storage groups, 1500 time series per storage group .
2.  jar : Write values to these 60000 time series every second .

**Screenshots**
![捕获](https://user-images.githubusercontent.com/49938137/100819375-fffd8980-3486-11eb-821b-42b77cf9dcc8.PNG)

**Additional context**
I know that iotdb will compress and store data at a certain frequency. Is the disappearance of historical data related to this?
In addition, jar occasionally reports exceptions
`org.apache.iotdb.db.exception.WriteProcessException: System rejected over 0ms`
Is the load too high?

**Comment by HTHou** [comment]
Hi, thank you so much for your feedback. 

The data missing is related to https://github.com/apache/iotdb/issues/2147
This is because after small files are being merged into a larger one. The new data file index is lost in memory.
This is fixed in rel/0.11 and master branch. Please package the rel/0.11 branch and try again.

The WriteProcessException could be avoid by increasing the following config in iotdb-engine.properties:

waiting_time_when_insert_blocked=100
max_waiting_time_when_insert_blocked=10000

**Comment by kohlersDagger** [comment]
Thanks ,  [the master branch at that time](https://github.com/apache/iotdb/tree/f6cd1f95fd58b7772c8e850e5496361a9875fcff) solved this problem .
Looking forward to your next update .
