### ISSUE TITLE
What is the difference between the last_value operator and the  last operator？

### ISSUE THREAD

**Issue by neuyilan** [apache/iotdb#2395]
I see there are two operators in IoTDB: last_value and last
I only see some differences in the output format. Are there any other differences?

![image](https://user-images.githubusercontent.com/6237070/103393155-4ca6b400-4b5c-11eb-9059-f9e41e96e49b.png)

**Comment by jixuan1989** [comment]
- `last` is an individual statement, while `last_value` is an aggregation function. That means, you can use `last_value` attached with `group by` statement. 

- if you have no filters (`where` clause, or just `where time > ?`), then use `last`, it is far faster than last_value.
Otherwise, you have to use `last_value`.

**Comment by neuyilan** [comment]
Got it, Thanks.
