### ISSUE TITLE
 Failed to execute goal org.apache.thrift.tools:maven-thrift-plugin:0.1.11:compile (generate-thrift-sources-java) on project iotdb-thrift: thrift did not exit cleanly. Review output for more information.

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [apache/iotdb#2443]
今天在使用mvn clean compile -pl server -am -DskipTests 编译iotdb报Failed to execute goal org.apache.thrift.tools:maven-thrift-plugin:0.1.11:compile (generate-thrift-sources-java) on project iotdb-thrift: thrift did not exit cleanly. Review output for more information.导致编译失败。

解决方式：查看/thrift/target/tools/thrift_0.12.0_0.13.0_mac.exe文件大小与pom文件的url地址访问下载的thrift_0.12.0_0.13.0_mac.exe文件大小进行比对，我遇到的就是通过mvn下载的只有2.1M 实际有5.3M。通过浏览器下载完替换为正常的就能编译通过

**Comment by CloudWise-Lukemiao** [comment]
解决方式：查看/thrift/target/tools/thrift_0.12.0_0.13.0_mac.exe文件大小与pom文件的url地址访问下载的thrift_0.12.0_0.13.0_mac.exe文件大小进行比对，我遇到的就是通过mvn下载的只有2.1M 实际有5.3M。通过浏览器下载完替换为正常的就能编译通过

**Comment by LeiRui** [comment]
Same issue on win10 with v0.13.0. 
The thrift download url for windows in pom.xml is "http://artfiles.org/apache.org/thrift/${thrift.version}/thrift-${thrift.version}.exe" with ${thrift.version}=0.14.1.
While the latest version is 0.16.0, so set thrift.version=0.16.0 and solve the problem.

**Comment by jixuan1989** [comment]
I do not know whether it is compatible to update thrift 0.14 to 0.16 directly..

Maybe we can use thrift 0.14.2: https://archive.apache.org/dist/thrift/0.14.2/thrift-0.14.2.exe

**Comment by 28723249** [comment]
Same problem on my win10, but with another cause: Missing the "Microsoft Visual C++ {version} Redistributable".
  I install the "Visual Studio Build Tool" and solve it.

  The reason is: thrift-{version}.exe is only a "prebuilt Thrift compiler", it depends on some libraries, see [here](https://thrift.apache.org/docs/install/windows.html).
  "Visual Studio Build Tool" can provide these libraries, download it from Microsoft website and install it as follows:
1. In tag workload, check "Desktop development ... C++", and "MSVC vxxx - VS20xx C++ x64/x86 Build Tool" in right side;
2. Install.

 Then, all is OK.
