### ISSUE TITLE
Introduce internalMNode type to avoid implementing MNode type directly

### ISSUE THREAD

**Issue by rhmangmang** [apache/iotdb#2485]

**Comment by samperson1997** [comment]
Hi @weizihan0110 , thanks a lot for pointing out this issue.

Actually, we have `InternalMNode` at the beginning of the design (and that's why it appeared in the design document).

Afterwards, after `Allow SubDevices in IoTDB` function is supported (in PR #1323), we noticed that all types of `MNode` extend `InternalMNode`, which extends `MNode`. Therefore, we refactored `MNode` by removing `InternalMNode` and including all its methods.

Here is the related PR: #1345. You could see the `InternalMNode.java` is totally deleted.

However, we only considered "sub-devices" at that time, without considering creating parent node. So this decision may be reverted. What do you think? Would you like to try and implement the function that you need?

**Comment by weizihan0110** [comment]
> Hi @weizihan0110 , thanks a lot for pointing out this issue.
> 
> Actually, we have `InternalMNode` at the beginning of the design (and that's why it appeared in the design document).
> 
> Afterwards, after `Allow SubDevices in IoTDB` function is supported (in PR #1323), we noticed that all types of `MNode` extend `InternalMNode`, which extends `MNode`. Therefore, we refactored `MNode` by removing `InternalMNode` and including all its methods.
> 
> Here is the related PR: #1345. You could see the `InternalMNode.java` is totally deleted.
> 
> However, we only considered "sub-devices" at that time, without considering creating parent node. So this decision may be reverted. What do you think? Would you like to try and implement the function that you need?

**Comment by weizihan0110** [comment]
> Hi @weizihan0110 , thanks a lot for pointing out this issue.
> 
> Actually, we have `InternalMNode` at the beginning of the design (and that's why it appeared in the design document).
> 
> Afterwards, after `Allow SubDevices in IoTDB` function is supported (in PR #1323), we noticed that all types of `MNode` extend `InternalMNode`, which extends `MNode`. Therefore, we refactored `MNode` by removing `InternalMNode` and including all its methods.
> 
> Here is the related PR: #1345. You could see the `InternalMNode.java` is totally deleted.
> 
> However, we only considered "sub-devices" at that time, without considering creating parent node. So this decision may be reverted. What do you think? Would you like to try and implement the function that you need?

Hi, Zesong, I have submitted a related PR at [ISSUE-2484] Fix creating timeseries error by using "create" or "insert" statement #2468. Could you have a review for it?
