### ISSUE TITLE
[Refactor Cluster] query performance improvement in cluster- branch analysis

### ISSUE THREAD

**Issue by chengjianyun** [apache/iotdb#4259]
We found the query performance is better on `cluster-` branch than `master` branch when we do performance verification for [the PR](https://github.com/apache/iotdb/pull/4079). Look the detail of performance test result in [the comment](https://github.com/apache/iotdb/pull/4079#issuecomment-952504612).

Here we start the issue to track where the performance gain generated.

## 10/28 2021
We guess the performance gain come from `client pool refactor` as we don't change the query logic except this one may have some impact. So I did the test: with and without `client pool refactor`. Test result as below.

### Environment
- branch: cluster-
- 3 nodes, 3 replica, multi-factor=1

- benchmark config: 
  - CLIENT_NUMBER=20
  - GROUP_NUMBER=20
  - DEVICE_NUMBER=100000
  - SENSOR_NUMBER=10
  - BATCH_SIZE=100
  - LOOP=100
 
### without client pool refactor
commit id: 4b34a9c
#### write
![no-commons-pool-1](https://user-images.githubusercontent.com/6150814/139244662-5f1f5987-0fd5-4a2a-a84f-68be1daa08d6.jpg)
#### refresh query(the first query task after write)
![no-commons-pool-query-1](https://user-images.githubusercontent.com/6150814/139244866-78b43e32-3cdf-4304-8866-e135e3ff088c.jpg)
#### second query (should hit cache)
![no-commons-pool-query-1-1](https://user-images.githubusercontent.com/6150814/139244956-4c51e512-1272-4b9d-bd40-8bbbe1124104.jpg)

### with client pool refactor
commit id: 19d2f70
#### write
![commons-pool-write-1](https://user-images.githubusercontent.com/6150814/139245146-d60ac953-01f9-48ab-bfa7-3d46ba97250a.jpg)

#### refresh query(the first query task after write)
![commons-pool-query-1](https://user-images.githubusercontent.com/6150814/139245209-7848d66f-de99-4d82-b5ea-7a26853109f3.jpg)

#### second query(should hit some cache)
![commons-pool-query-1-1](https://user-images.githubusercontent.com/6150814/139245230-7f460920-974a-4095-ad59-abfb7d1410ec.jpg)

**Comment by LebronAl** [comment]
## Environment:
- 16 Core 
- 32G memory
- 300G HDD
- 10000 Mb/s
- Ubuntu 18.04.5 LTS

## Version:
- IoTDB master: 0013531610fea6b86ca53c259081abe4b0b78b68
- IoTDB cluster-: 886d06b5ba97407d0a45a58fe843caecf1a18f4e
- Benchmark master: 3ef6dca56ac8f8d197cd180fbfbe8cabdd6cc60d

## Cluster Configuration:
- default_replica_num = 1
- seed_nodes = "172.20.70.66:9003,172.20.70.67:9003,172.20.70.68:9003"

## Result
### master:
- write:
```
----------------------Main Configurations----------------------
CREATE_SCHEMA=true
START_TIME=2018-9-20T00:00:00+08:00
INSERT_DATATYPE_PROPORTION=1:1:1:1:1:1
BATCH_SIZE_PER_WRITE=10
IS_CLIENT_BIND=true
LOOP=300
IS_OUT_OF_ORDER=false
IS_REGULAR_FREQUENCY=true
GROUP_NUMBER=20
IS_RECENT_QUERY=false
QUERY_INTERVAL=250000
SENSOR_NUMBER=10
RESULT_PRECISION=0.1%
POINT_STEP=5000
CLIENT_NUMBER=20
SG_STRATEGY=mod
REAL_INSERT_RATE=1.0
OUT_OF_ORDER_MODE=0
DBConfig=
  DB_SWITCH=IoTDB-012-SESSION_BY_TABLET
  HOST=[172.20.70.66]
  PORT=[6667]
  USERNAME=root
  PASSWORD=root
  DB_NAME=test
  TOKEN=token
DOUBLE_WRITE=false
BENCHMARK_WORK_MODE=testWithDefaultPath
OP_INTERVAL=0
OPERATION_PROPORTION=1:0:0:0:0:0:0:0:0:0:0
DEVICE_NUMBER=100000
OUT_OF_ORDER_RATIO=0.5
BENCHMARK_CLUSTER=false
IS_DELETE_DATA=true
IS_SENSOR_TS_ALIGNMENT=true
---------------------------------------------------------------
```
![image](https://user-images.githubusercontent.com/32640567/139905643-cda2d0c9-c0ba-451e-9ecb-bb569080101d.png)
- read:
```
----------------------Main Configurations----------------------
CREATE_SCHEMA=false
START_TIME=2018-9-20T00:00:00+08:00
INSERT_DATATYPE_PROPORTION=1:1:1:1:1:1
BATCH_SIZE_PER_WRITE=10
IS_CLIENT_BIND=true
LOOP=3000
IS_OUT_OF_ORDER=false
IS_REGULAR_FREQUENCY=true
GROUP_NUMBER=20
IS_RECENT_QUERY=false
QUERY_INTERVAL=250000
SENSOR_NUMBER=10
RESULT_PRECISION=0.1%
POINT_STEP=5000
CLIENT_NUMBER=20
SG_STRATEGY=mod
REAL_INSERT_RATE=1.0
OUT_OF_ORDER_MODE=0
DBConfig=
  DB_SWITCH=IoTDB-012-SESSION_BY_TABLET
  HOST=[172.20.70.66]
  PORT=[6667]
  USERNAME=root
  PASSWORD=root
  DB_NAME=test
  TOKEN=token
DOUBLE_WRITE=false
BENCHMARK_WORK_MODE=testWithDefaultPath
OP_INTERVAL=0
OPERATION_PROPORTION=0:1:1:1:1:1:1:1:1:1:1
DEVICE_NUMBER=100000
OUT_OF_ORDER_RATIO=0.5
BENCHMARK_CLUSTER=false
IS_DELETE_DATA=false
IS_SENSOR_TS_ALIGNMENT=true
---------------------------------------------------------------
```
![image](https://user-images.githubusercontent.com/32640567/139905701-300823be-a5d7-4001-91e5-d25e57368071.png)
- read twice(with cache):
![image](https://user-images.githubusercontent.com/32640567/139905872-ddd9f328-75f3-4990-9afb-a7031da87be6.png)
### master:
- write:
```
----------------------Main Configurations----------------------
CREATE_SCHEMA=true
START_TIME=2018-9-20T00:00:00+08:00
INSERT_DATATYPE_PROPORTION=1:1:1:1:1:1
BATCH_SIZE_PER_WRITE=10
IS_CLIENT_BIND=true
LOOP=300
IS_OUT_OF_ORDER=false
IS_REGULAR_FREQUENCY=true
GROUP_NUMBER=20
IS_RECENT_QUERY=false
QUERY_INTERVAL=250000
SENSOR_NUMBER=10
RESULT_PRECISION=0.1%
POINT_STEP=5000
CLIENT_NUMBER=20
SG_STRATEGY=mod
REAL_INSERT_RATE=1.0
OUT_OF_ORDER_MODE=0
DBConfig=
  DB_SWITCH=IoTDB-012-SESSION_BY_TABLET
  HOST=[172.20.70.66]
  PORT=[6667]
  USERNAME=root
  PASSWORD=root
  DB_NAME=test
  TOKEN=token
DOUBLE_WRITE=false
BENCHMARK_WORK_MODE=testWithDefaultPath
OP_INTERVAL=0
OPERATION_PROPORTION=1:0:0:0:0:0:0:0:0:0:0
DEVICE_NUMBER=100000
OUT_OF_ORDER_RATIO=0.5
BENCHMARK_CLUSTER=false
IS_DELETE_DATA=true
IS_SENSOR_TS_ALIGNMENT=true
---------------------------------------------------------------
```
![image](https://user-images.githubusercontent.com/32640567/139906822-0f86c8d2-35a4-4ce5-b511-9046130a372b.png)
- read:
```
----------------------Main Configurations----------------------
CREATE_SCHEMA=false
START_TIME=2018-9-20T00:00:00+08:00
INSERT_DATATYPE_PROPORTION=1:1:1:1:1:1
BATCH_SIZE_PER_WRITE=10
IS_CLIENT_BIND=true
LOOP=3000
IS_OUT_OF_ORDER=false
IS_REGULAR_FREQUENCY=true
GROUP_NUMBER=20
IS_RECENT_QUERY=false
QUERY_INTERVAL=250000
SENSOR_NUMBER=10
RESULT_PRECISION=0.1%
POINT_STEP=5000
CLIENT_NUMBER=20
SG_STRATEGY=mod
REAL_INSERT_RATE=1.0
OUT_OF_ORDER_MODE=0
DBConfig=
  DB_SWITCH=IoTDB-012-SESSION_BY_TABLET
  HOST=[172.20.70.66]
  PORT=[6667]
  USERNAME=root
  PASSWORD=root
  DB_NAME=test
  TOKEN=token
DOUBLE_WRITE=false
BENCHMARK_WORK_MODE=testWithDefaultPath
OP_INTERVAL=0
OPERATION_PROPORTION=0:1:1:1:1:1:1:1:1:1:1
DEVICE_NUMBER=100000
OUT_OF_ORDER_RATIO=0.5
BENCHMARK_CLUSTER=false
IS_DELETE_DATA=false
IS_SENSOR_TS_ALIGNMENT=true
---------------------------------------------------------------
```
![image](https://user-images.githubusercontent.com/32640567/139906921-7cfb3471-7e03-4ffc-99ca-e8ea3e764660.png)
- read twice:
![image](https://user-images.githubusercontent.com/32640567/139906955-c9010036-3e9f-4de2-bc97-01b8492e91d2.png)

## Conclusion

In order to more objectively measure the performance comparison between `master` and `cluster-`, I conducted the above test. The test results show that the read and write performance of `cluster-` and `master` branches is basically the same, which is basically in line with our changes.

As for why @chengjianyun tests for a huge performance difference,  I suspect there are two reasons:
1. The query time is too short, only a few seconds of the query, such a short time test results are often inaccurate. So I made the query loop larger during above test.
2. Leader distribution in the case of `default_replica_num=3` may also affect read and write performance. So I chose `default_replica_num=1` for comparison
